CREATE TABLE jobs (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, job TEXT NOT NULL, start_date TEXT, end_date TEXT, key_id INTEGER);
CREATE TABLE projects (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, project TEXT NOT NULL, job_id INTEGER, explanation TEXT NOT NULL, key_id INTEGER);
CREATE TABLE experiences (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, job_id INTEGER NOT NULL, summary TEXT NOT NULL, key_id INTEGER);
CREATE TABLE skills (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, skill TEXT, key_id INTEGER);
CREATE TABLE keywords (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, key TEXT NOT NULL);
CREATE TABLE synonyms (key_id INTEGER NOT NULL, synonym TEXT NOT NULL);